name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.0' # Matches go.mod
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev pkg-config
        
        # Ensure webkit2gtk-4.0 compatibility for older Wails versions
        if ! pkg-config --exists webkit2gtk-4.0; then
          echo "Creating webkit2gtk-4.0 compatibility..."
          sudo mkdir -p /usr/lib/x86_64-linux-gnu/pkgconfig
          
          # Create a compatibility .pc file
          sudo cp /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.1.pc /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc || true
          if [ -f /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc ]; then
            sudo sed -i 's/webkit2gtk-4\.1/webkit2gtk-4.0/g' /usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc
          fi
          
          # Create library symlinks for the linker
          for lib in /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so*; do
            if [ -f "$lib" ]; then
              target_lib=$(echo "$lib" | sed 's/4\.1/4.0/g')
              sudo ln -sf "$lib" "$target_lib" || true
              echo "Created symlink: $lib -> $target_lib"
            fi
          done
        fi
        
        # Verify the setup
        pkg-config --exists webkit2gtk-4.0 && echo "webkit2gtk-4.0 is available" || echo "WARNING: webkit2gtk-4.0 still not found"
    
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    - name: Build Wails app
      run: wails build -clean
    
    - name: Prepare artifact info (Windows)
      if: matrix.os == 'windows-latest'
      id: prepare-windows
      shell: pwsh
      run: |
        echo "release_name=klisse-windows-amd64.exe" >> $env:GITHUB_OUTPUT
        echo "release_path=build/bin/klisse.exe" >> $env:GITHUB_OUTPUT
    
    - name: Prepare artifact info (Linux)
      if: matrix.os == 'ubuntu-latest'
      id: prepare-linux
      run: |
        echo "release_name=klisse-linux-amd64" >> $GITHUB_OUTPUT
        echo "release_path=build/bin/klisse" >> $GITHUB_OUTPUT
    
    - name: Prepare artifact info (macOS)
      if: matrix.os == 'macos-latest'
      id: prepare-macos
      run: |
        ditto -c -k --sequesterRsrc --keepParent build/bin/klisse.app klisse-macos-universal.zip
        echo "release_name=klisse-macos-universal.zip" >> $GITHUB_OUTPUT
        echo "release_path=klisse-macos-universal.zip" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.prepare-windows.outputs.release_name || steps.prepare-linux.outputs.release_name || steps.prepare-macos.outputs.release_name }}
        path: ${{ steps.prepare-windows.outputs.release_path || steps.prepare-linux.outputs.release_path || steps.prepare-macos.outputs.release_path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/klisse-windows-amd64.exe/klisse-windows-amd64.exe
            artifacts/klisse-linux-amd64/klisse-linux-amd64
            artifacts/klisse-macos-universal.zip/klisse-macos-universal.zip